### ISSUE TITLE
Pythia Include Paths

### ISSUE THREAD

**Issue by smaurus** [smash-transport/smash#1]
Hi,

I installed SMASH when i found a Problem:

- If you install SMASH on a system with 2 Pythias, it can happen that the library is taken from one path and the config-executable from another:

//Path to a program.
Pythia_CONFIG_EXECUTABLE:FILEPATH=/location1/pythia8235/bin/pythia8-config
//Path to a library.
Pythia_LIBRARY:FILEPATH=/location2/pythia8235/lib/libpythia8.a

while compiling no errors occurs, but during run-time it crashes. 
If both locations are the same no problem occurs.
Maybe an error or warning before compiling would help.

And again thanks to Dmytro for helping.

**Comment by elfnerhannah** [comment]
Thanks for bringing this to our attention, a warning is now generated in the newest release SMASH-1.6.
