### ISSUE TITLE
error  from pythia

### ISSUE THREAD

**Issue by TakeLeastAction** [smash-transport/smash#10]
I have installed smash according to the manu. In the config.yaml, I set 'Sqrtsnn: 7.7', then run ./smash
It gives the following information:

_PYTHIA Warning in JunctionSplitting::CheckColours: not-a-number energy/momentum/mass  
 PYTHIA Error in HadronLevel::next: failed colour/junction check  
 PYTHIA Error in Pythia::forceHadronLevel: hadronLevel failed; try again  
 PYTHIA Abort from Pythia::forceHadronLevel: hadronLevel failed; giving up  
PYTHIA Error in MiniStringFragmentation::fragment: no 1- or 2-body state found above mass threshold_  

smash continues to run till the end.

What does this information mean? Does this affect the final results?

**Comment by justinmohs** [comment]
Thank you for using smash and creating this issue.
You don't need to worry about the Pythia warnings and errors. They should not affect the results.
When Pythia is applied for calculating the final state of some interaction and errors, we recalculate that interaction.

**Comment by TakeLeastAction** [comment]
Thank you for the information
