### ISSUE TITLE
Number of final interactions in output files

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#12]
Hi! I have a little question/wish about .root files and Number of final interactions in this files.

I am interested about the information about number of interactions in the single one collisions,  and I've tried to get this number from .root files - "Particles.root" and "Collisions.root". Nevertheless, I've found that there is no such brunch in trees of this files. Yes, there is the "ev" branch in "Particles.root" with # of events as histogram X-axis and with number of interactions as bin contents. But if we use TChain-class (instead the only one file's tree), the method "find bin and get its content" doesn't work, because all trees are merging when we use TChain. Of course, there is a few methods from which we can extract the necessary information, but all this methods seem to be inaccurate and slow. 

So my question is: can we extract the number of interactions of the concrete event if we read TChain of files by some simple way?
Also I think that it would be much more conveniently to have the branch with number of interactions in event in the same fashion as the "impact" branch constructed (the "Entry" of histo is the number of event and X-axis is the "Impact"-parameter).

Thank you in advance for your reply.

**Comment by vks** [comment]
Can't you just count the number of entries in "Collisions.root"?

As a workaround, you could also use the final interaction number from SMASH's terminal output:

```
[15'59'43]  INFO      Experiment     : Time real: 72.0358 [s]
[15'59'43]  INFO      Experiment     : Final interaction number: 3271
```

**Comment by stdnmr** [comment]
Since two solutions were provided and due to the inactivity for half a year, the issue is closed.
