### ISSUE TITLE
Various fixes - mainly to enable using SMASH as a callable library in 3rd party code

### ISSUE THREAD

**Issue by cholmcc** [smash-transport/smash#15]
Hi, 

I attach a patch which address a few tings in SMASH 

 - The macro `source_location` conflicts with `boost::source_location`.  That is, if defined, it will make the compiler choke on bad syntax when `source_location` is expanded in `boost::source_location`.  The patch fixes this by renaming the macro to `_source_location` (it should probably be `SMASH_source_location` to make it more distinct) 
 - Install all headers, libraries, and binaries in `${CMAKE_INSTALL_PREFIX}/{include,lib,bin}` as well as example inputs in `${CMAKE_INSTALL_PREFIX}/share/smash`.  This makes it possible for 3rd partiy applications to use the code from predictable locations. 
 - Add `Pythia_LIBDIR` to link directories (otherwise the linker may not find `lpythia8`) 
 - Remove explicit `-std=c++11` from `CXXFLAGS`.  This can make it difficult to link with other libraries in 3rd party applicaitons.  The ABI of GNU C++11 isn't compatible with the C++14+ ABI, and one may want to pass `-std=c++17` to link with other libraries (e.g., HepMC3 or Rivet).  Users can set `CMAKE_CXX_COMPILER_FLAGS` as needed.  Another option would be to define a CMake Variable (say `CMAKE_CXX_STANDARD_VERSION`) by default set to `c++11` but overwritable by the user. 
 - _Always_ initialize `Experiment<T>::nucleon_has_interacted_` in `Experiment<T>::initialize_new_event` - otherwise later stages may SIGSEGV.  I know that you do this expicitly in `Experiment<T>::run` but if one wants to use SMASH as an external  library, then that is not an option since the member is `private`.  In any case, it does not hurt to explicitly initialize it. 
 
All these changes mainly aim at enabling the use of SMASH in thrid party applications.  For example, one can define a program that let's SMASH generate an HepMC3 event in memory which Rivet then analyses directly from memory.   This avoids the _very_ costly I/O of HepMC events to disk or FIFO (at least a factor 10 speed up)

.  I attach an example of such a program (it works - try it with your favorite Rivet Analysis). 

Yours, 

Christian 
[smash_patch_and_rivet.tar.gz](https://github.com/smash-transport/smash/files/5971229/smash_patch_and_rivet.tar.gz)

**Comment by cholmcc** [comment]
Oh, and I added member functions to `Experiment<T>` that returns `npart_projectle` and `npart_target` by summing entries in `nucleon_has_interacted_`.  I don't know how to get `Ncoll` though. 

And one more thing - the compat std::make_unique is broken when compiling with C++17 - Fixed that by preprocessor guards.

**Comment by stdnmr** [comment]
Thanks, Christian, for taking the time to improve the use of SMASH in 3rd party application. Your changes sound good. If you like, you can directly open a pull request with your changes. Otherwise, I would do this and put you as an co-author to the commit. What would you prefer?

**Comment by cholmcc** [comment]
Hi  Jan,

I prefer you do the patching.  Making a PR will take a little time to do,
so I think that is the fastest approach.

Yours,

Christian Holm Christensen --------------------
Sankt Hans Gade 23 4, DK-2200 Copenhagen
+4524618591, cern.ch/cholm

**Comment by stdnmr** [comment]
Hi Christian, so I see you already went ahead and did the PRs anyway. Should I still assist you with opening PRs for the remaining changes? I see at the moment the initialization of `nucleon_has_interacted_` is not filed for example.

**Comment by cholmcc** [comment]
Hi Jan, 

I've made PRs for all the changes (plus a new thing to allow setting `E_Kin` or `P_Lab` per beam - needed for LHC p-Pb simulations).   All the changes are there - see pull requests #16, #17, #18, and #19 

The reason I finally made PRs anyway as not due to impatience :-) but because I realised that more was needed.

**Comment by stdnmr** [comment]
Very nice. Yes, I saw the additional changes 👍 I just wanted to make sure that we do not do the same work twice ;-)

**Comment by doliinychenko** [comment]
I didn't dive deep into the issue, so maybe what I want to suggest is already done. But anyway: using SMASH as a 3rd party library I met nasty errors, when ParticleType and DecayModes are initialized, but the cross section tabulation is not done. Either SMASH should package all initializations into one public function or at least fail more graciously if tabulations are not initialized -- just nameless segfault is not good.

**Comment by vks** [comment]
@doliinychenko I agree that we should at least fail with a panic. Could you maybe open an issue describing the steps to reproduce the segfault? Thanks!

**Comment by stdnmr** [comment]
Done with #24.
