### ISSUE TITLE
Troubles with SMASH building

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#2]
Hello!

Trying to build SMASH, I've faced with the problem (see below). What can cause this and how can I fix it??? Thanks for future answer.

My terminal:

`[ 22%] Building CXX object src/CMakeFiles/objlib.dir/configuration.cc.o
In file included from /home/vlad/HEP/SMASH_generator/boost_1_49_0/boost/filesystem.hpp:35:0,
                 from /home/vlad/HEP/smash_1.6/src/configuration.cc:17:
/home/vlad/HEP/SMASH_generator/boost_1_49_0/boost/filesystem/v3/path.hpp:732:24: error: ‘path’ is already declared in this scope
     using filesystem3::path;
                        ^~~~
/home/vlad/HEP/smash_1.6/src/configuration.cc:89:1: error: prototype for ‘smash::Configuration::Configuration(const boost::filesystem3::path&)’ does not match any in class ‘smash::Configuration’
 Configuration::Configuration(const bf::path &path)
 ^~~~~~~~~~~~~
In file included from /home/vlad/HEP/smash_1.6/src/configuration.cc:10:0:
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:969:3: error: candidates are: smash::Configuration::Configuration(const YAML::Node&)
   Configuration(const YAML::Node &node)  // NOLINT(runtime/explicit) : see above
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:823:3: error:                 smash::Configuration::Configuration(smash::Configuration&&)
   Configuration(Configuration &&) = default;
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:818:3: error:                 smash::Configuration::Configuration(const smash::Configuration&)
   Configuration(const Configuration &) = default;
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:803:12: error:                 smash::Configuration::Configuration(const boost::filesystem::path&, const boost::filesystem::path&)
   explicit Configuration(const bf::path &path, const bf::path &filename);
            ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:794:12: error:                 smash::Configuration::Configuration(const boost::filesystem::path&)
   explicit Configuration(const bf::path &path);
            ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/configuration.cc:93:1: error: prototype for ‘smash::Configuration::Configuration(const boost::filesystem3::path&, const boost::filesystem3::path&)’ does not match any in class ‘smash::Configuration’
 Configuration::Configuration(const bf::path &path, const bf::path &filename) {
 ^~~~~~~~~~~~~
In file included from /home/vlad/HEP/smash_1.6/src/configuration.cc:10:0:
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:969:3: error: candidates are: smash::Configuration::Configuration(const YAML::Node&)
   Configuration(const YAML::Node &node)  // NOLINT(runtime/explicit) : see above
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:823:3: error:                 smash::Configuration::Configuration(smash::Configuration&&)
   Configuration(Configuration &&) = default;
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:818:3: error:                 smash::Configuration::Configuration(const smash::Configuration&)
   Configuration(const Configuration &) = default;
   ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:803:12: error:                 smash::Configuration::Configuration(const boost::filesystem::path&, const boost::filesystem::path&)
   explicit Configuration(const bf::path &path, const bf::path &filename);
            ^~~~~~~~~~~~~
/home/vlad/HEP/smash_1.6/src/include/smash/configuration.h:794:12: error:                 smash::Configuration::Configuration(const boost::filesystem::path&)
   explicit Configuration(const bf::path &path);
            ^~~~~~~~~~~~~
src/CMakeFiles/objlib.dir/build.make:190: recipe for target 'src/CMakeFiles/objlib.dir/configuration.cc.o' failed
make[2]: *** [src/CMakeFiles/objlib.dir/configuration.cc.o] Error 1
CMakeFiles/Makefile2:1561: recipe for target 'src/CMakeFiles/objlib.dir/all' failed
make[1]: *** [src/CMakeFiles/objlib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by stdnmr** [comment]
Hi, thanks for writing. In cases with error message like you posted, it often helps to delete the build folder and start with a completely clean one. Could you try that?

**Comment by gamejad** [comment]
> Hi, thanks for writing. In cases with error message like you posted, it often helps to delete the build folder and start with a completely clean one. Could you try that?

Yes, I've tried that - but there is no positive changes. Folder remaking fixes nothing.

This problem was fixed by using boost v. 1_50 (not 1_49). But there is other problem emerged. It is compilation problem related to smash_sanitizer

`[ 46%] Linking CXX executable ../smash_sanitizer
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_has_events_(boost::filesystem::path, std::fpos<__mbstate_t>)':
/home/vlad/HEP/smash/src/listmodus.cc:358: undefined reference to `boost::filesystem::path::filename() const'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:553: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash/src/listmodus.cc:271: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash/src/listmodus.cc:275: undefined reference to `boost::filesystem::path::filename() const'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash/src/listmodus.cc:278: undefined reference to `boost::filesystem::path::filename() const'
libsmash.a(listmodus.cc.o): In function `smash::ListModus::next_event_[abi:cxx11]()':
/home/vlad/HEP/smash/src/listmodus.cc:323: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `boost::filesystem::operator/(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash/src/smash.cc:405: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:553: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash/src/smash.cc:244: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:662: undefined reference to `boost::filesystem::path::compare(boost::filesystem::path const&) const'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash/src/smash.cc:496: undefined reference to `boost::filesystem::path::filename() const'
/home/vlad/HEP/smash/src/smash.cc:495: undefined reference to `boost::filesystem::path::parent_path() const'
CMakeFiles/smash_sanitizer.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:409: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:523: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(configuration.cc.o): In function `smash::Configuration::Configuration(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(configuration.cc.o): In function `smash::Configuration::Configuration(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(filelock.cc.o): In function `smash::FileLock::~FileLock()':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:620: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(hadgas_eos.cc.o): In function `smash::EosTable::compile_table(smash::HadronGasEos&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(oscaroutput.cc.o): In function `smash::OscarOutput<(smash::OscarOutputFormat)1, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(oscaroutput.cc.o): In function `smash::OscarOutput<(smash::OscarOutputFormat)0, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(oscaroutput.cc.o): In function `smash::OscarOutput<(smash::OscarOutputFormat)2, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(oscaroutput.cc.o): In function `smash::OscarOutput<(smash::OscarOutputFormat)1, 8>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(oscaroutput.cc.o): In function `smash::OscarOutput<(smash::OscarOutputFormat)0, 8>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(oscaroutput.cc.o):/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: more undefined references to `boost::filesystem::path::operator/=(boost::filesystem::path const&)' follow
libsmash.a(setup_particles_decaymodes.cc.o): In function `smash::load_particles_and_decaymodes[abi:cxx11](char const*, char const*)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:404: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(thermodynamicoutput.cc.o): In function `smash::ThermodynamicOutput::ThermodynamicOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(vtkoutput.cc.o): In function `smash::VtkOutput::write(smash::Particles const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(rootoutput.cc.o): In function `smash::RootOutput::~RootOutput()':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:632: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
libsmash.a(rootoutput.cc.o): In function `smash::RootOutput::RootOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(binaryoutput.cc.o): In function `smash::BinaryOutputCollisions::BinaryOutputCollisions(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(binaryoutput.cc.o): In function `smash::BinaryOutputParticles::BinaryOutputParticles(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/path.hpp:695: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
libsmash.a(file.cc.o): In function `smash::RenamingFilePtr::~RenamingFilePtr()':
/home/vlad/HEP/SMASH_generator/boost_1_57_0/boost/filesystem/operations.hpp:632: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/smash_sanitizer.dir/build.make:106: recipe for target 'smash_sanitizer' failed
make[2]: *** [smash_sanitizer] Error 1
CMakeFiles/Makefile2:1481: recipe for target 'src/CMakeFiles/smash_sanitizer.dir/all' failed
make[1]: *** [src/CMakeFiles/smash_sanitizer.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`
This problem doesn't fix by using newer versions of boost (1_53 and 1_57 doesn't work).

**Comment by vks** [comment]
Could you please try to use `make smash -j8` to avoid building `smash_sanitizer`?

**Comment by gamejad** [comment]
> Could you please try to use `make smash -j8` to avoid building `smash_sanitizer`?

Well, I've got this

`vlad@vlad-Lenovo-ideapad-330-15ARR:~/HEP/smash-SMASH-1.6/build$ make smash
[ 54%] Built target objlib
[ 57%] Built target einhard
[ 82%] Built target yaml-cpp
[ 85%] Built target cuhre
[ 91%] Built target suave
[ 94%] Built target vegas
[ 97%] Built target divonne
Scanning dependencies of target smash
[100%] Building CXX object src/CMakeFiles/smash.dir/smash.cc.o
[100%] Linking CXX executable ../smash
CMakeFiles/smash.dir/smash.cc.o: In function `boost::filesystem::operator/(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:139: undefined reference to `boost::filesystem::path::codecvt()'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash-SMASH-1.6/src/smash.cc:405: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:429: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash-SMASH-1.6/src/smash.cc:244: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:202: undefined reference to `boost::filesystem::path::codecvt()'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:202: undefined reference to `boost::filesystem::path::codecvt()'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:615: undefined reference to `boost::filesystem::path::compare(boost::filesystem::path const&) const'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/smash-SMASH-1.6/src/smash.cc:496: undefined reference to `boost::filesystem::path::filename() const'
/home/vlad/HEP/smash-SMASH-1.6/src/smash.cc:495: undefined reference to `boost::filesystem::path::parent_path() const'
CMakeFiles/smash.dir/smash.cc.o: In function `main':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:399: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:294: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_has_events_(boost::filesystem::path, std::fpos<__mbstate_t>)':
/home/vlad/HEP/smash-SMASH-1.6/src/listmodus.cc:358: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:429: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash-SMASH-1.6/src/listmodus.cc:271: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash-SMASH-1.6/src/listmodus.cc:275: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::file_path_(int)':
/home/vlad/HEP/smash-SMASH-1.6/src/listmodus.cc:278: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/objlib.dir/listmodus.cc.o: In function `smash::ListModus::next_event_[abi:cxx11]()':
/home/vlad/HEP/smash-SMASH-1.6/src/listmodus.cc:323: undefined reference to `boost::filesystem::path::filename() const'
CMakeFiles/objlib.dir/binaryoutput.cc.o: In function `smash::BinaryOutputCollisions::BinaryOutputCollisions(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/binaryoutput.cc.o: In function `smash::BinaryOutputParticles::BinaryOutputParticles(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/configuration.cc.o: In function `smash::Configuration::Configuration(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/configuration.cc.o: In function `smash::Configuration::Configuration(boost::filesystem::path const&, boost::filesystem::path const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/file.cc.o: In function `smash::RenamingFilePtr::~RenamingFilePtr()':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:508: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/filelock.cc.o: In function `smash::FileLock::~FileLock()':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:496: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/hadgas_eos.cc.o: In function `smash::EosTable::compile_table(smash::HadronGasEos&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/oscaroutput.cc.o: In function `smash::OscarOutput<(smash::OscarOutputFormat)1, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/oscaroutput.cc.o: In function `smash::OscarOutput<(smash::OscarOutputFormat)0, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/oscaroutput.cc.o: In function `smash::OscarOutput<(smash::OscarOutputFormat)2, 1>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/oscaroutput.cc.o: In function `smash::OscarOutput<(smash::OscarOutputFormat)1, 8>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/oscaroutput.cc.o: In function `smash::OscarOutput<(smash::OscarOutputFormat)0, 8>::OscarOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/oscaroutput.cc.o:/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: more undefined references to `boost::filesystem::path::operator/=(boost::filesystem::path const&)' follow
CMakeFiles/objlib.dir/setup_particles_decaymodes.cc.o: In function `smash::load_particles_and_decaymodes[abi:cxx11](char const*, char const*)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:289: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/thermodynamicoutput.cc.o: In function `smash::ThermodynamicOutput::ThermodynamicOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/vtkoutput.cc.o: In function `smash::VtkOutput::write(smash::Particles const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:139: undefined reference to `boost::filesystem::path::codecvt()'
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
CMakeFiles/objlib.dir/rootoutput.cc.o: In function `smash::RootOutput::~RootOutput()':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/operations.hpp:508: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
CMakeFiles/objlib.dir/rootoutput.cc.o: In function `smash::RootOutput::RootOutput(boost::filesystem::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, smash::OutputParameters const&)':
/home/vlad/HEP/SMASH_generator/boost_1_53_0/boost/filesystem/path.hpp:648: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/smash.dir/build.make:227: recipe for target 'smash' failed
make[3]: *** [smash] Error 1
CMakeFiles/Makefile2:1524: recipe for target 'src/CMakeFiles/smash.dir/all' failed
make[2]: *** [src/CMakeFiles/smash.dir/all] Error 2
CMakeFiles/Makefile2:1536: recipe for target 'src/CMakeFiles/smash.dir/rule' failed
make[1]: *** [src/CMakeFiles/smash.dir/rule] Error 2
Makefile:669: recipe for target 'smash' failed
make: *** [smash] Error 2
`

**Comment by vks** [comment]
I tried compiling SMASH with a custom-built boost 1.50 and I was not able to reproduce your problem. I suspect that the boost version you are including is different from the one you are linking against. (Note that the boost versions in the error messages are different from the ones you say you are using.)

Could you please try the following steps that worked for me?

```bash
# Download boost 1.50.0, or any version >= 1.49
tar xf boost_1_50_0.tar.bz2  # or similar   
cd boost_1_50_0   
cd tools/build/v2   
sh bootstrap.sh   
cd ../../..   
./tools/build/v2/b2 --with-filesystem --with-system variant=release   
export BOOST_ROOT=$(pwd)      
cd ..                               
mkdir smash_build && cd smash_build
cmake /path/to/smash -DBOOST_ROOT=$BOOST_ROOT -DPythia_CONFIG_EXECUTABLE=/path/to/pythia/bin/pythia8-config
make smash -j8
./smash
```

**Comment by gamejad** [comment]
> I tried compiling SMASH with a custom-built boost 1.50 and I was not able to reproduce your problem. I suspect that the boost version you are including is different from the one you are linking against. (Note that the boost versions in the error messages are different from the ones you say you are using.)
> 
> Could you please try the following steps that worked for me?
> 
> ```shell
> # Download boost 1.50.0, or any version >= 1.49
> tar xf boost_1_50_0.tar.bz2  # or similar   
> cd boost_1_50_0   
> cd tools/build/v2   
> sh bootstrap.sh   
> cd ../../..   
> ./tools/build/v2/b2 --with-filesystem --with-system variant=release   
> export BOOST_ROOT=$(pwd)      
> cd ..                               
> mkdir smash_build && cd smash_build
> cmake /path/to/smash -DBOOST_ROOT=$BOOST_ROOT -DPythia_CONFIG_EXECUTABLE=/path/to/pythia/bin/pythia8-config
> make smash -j8
> ./smash
> ```
> 
> (It is important to start with a fresh build.)

Now It works!!! Smash was built) Thank you very much!
