### ISSUE TITLE
SMASH data - (how to) extract particle charge from .root file?

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#4]
Hello!

I've generated some data and saved it as .root file. I can extract momenta, coordinates and PID's of final particles and use it to find (pseudo)rapidities, pT, phi, etc. But I also don't understand how to extract electric charge. How can I do it? 

Example of .cxx file I use to get some histograms is below:
`
#include "TRandom3.h"
#include "TFile.h"

#include "TH1.h"
#include "TH1D.h"
#include "TH2D.h"
#include "TH3.h"
#include "TTree.h"

#include "TF1.h"
#include "TCanvas.h"
#include "TPad.h"
#include "TMath.h"
#include "TStyle.h"
#include "TLegend.h"
#include "TRandom3.h"
#include "TString.h"

#include "TStyle.h"
#include "TGraphAsymmErrors.h"
#include "TGraphErrors.h"
#include "TLatex.h"

#include "TH1.h"
#include "TH1D.h"

#include <iostream>
using namespace std;

double Pt(Double_t a, Double_t b) // func. for abs. value of particle pT
{
  double c=sqrt(a*a+b*b);
  return c;
}

double P_abs(Double_t a, Double_t b, Double_t c)   // func. for abs. value of particle momentum
{
  double p = sqrt(a*a+b*b+c*c);
  return p;
}

double  Y_Eta(Double_t a, Double_t b) // func. for particle rapidity and/or pseudorapidity
{
  double c=0.5*log((a+b)/(a-b));
  return c;
}

double Phi(Double_t a, Double_t b)  // func. for particle azimuth angle in momenta space
{
  double c = atan2(b, a);
  return c;
}

void extract_events_tracks()
{
    // ##### open file and get tree, get branches
    TFile *file = new TFile( "/home/vlad/HEP/smash/smash_build/data/26/Particles.root" );  //path to data file
    TTree *tree = (TTree*)file->Get("particles");

    const int NMaxTrack = 15000;
    Double_t p0[NMaxTrack];
    Double_t px[NMaxTrack];
    Double_t py[NMaxTrack];
    Double_t pz[NMaxTrack]; //
    Int_t pdgcode[NMaxTrack];
    Int_t npart = 0;

    tree->SetBranchAddress( "npart",       &npart   );
    tree->SetBranchAddress( "p0",          p0       );
    tree->SetBranchAddress( "px",          px       );
    tree->SetBranchAddress( "py",          py       );
    tree->SetBranchAddress( "pz",          pz       );
    tree->SetBranchAddress( "pdgcode",     pdgcode  );

    // ##### prepare some histos to fill:
    TH1D *fHistPt = new TH1D("fHistPt", "p_{T} distribution;p_{T} (GeV/c);dN/dp_{T}", 100, 0, 5 );
    TH1D *fHistEta = new TH1D("fHistEta", "#eta distribution;#eta (GeV/c);dN/d#eta", 100, -5, 5 );
    TH1D *fHistY = new TH1D("fHistY", "Y distribution;Y (GeV/c);dN/dY", 100, -5, 5 );
    TH1D *fHistP_abs = new TH1D("fHistP_abs", "P_abs distribution;P_abs (GeV/c);dN/dP_abs", 100, 0, 5 );
    TH1D *fHistPhi = new TH1D("fHistPhi", "#phi distribution;#phi (GeV/c);dN/d#phi", 100, -4, 4 );

    // ##### event loop
    int nEvents = tree->GetEntries();
//    int nEvents = 20000;
    for ( int iEvent = 0; iEvent < nEvents; iEvent++)
    {
        tree->GetEntry(iEvent);

        if ( iEvent % 100 == 0 )
            cout << "processing " << (int)iEvent << "\r"; cout.flush();

        for ( int iTrack = 0; iTrack < npart; iTrack++ )
        {
            //int id = iTrack;
            double p_abs;
            double pt;
            double phi;
            double y;
            double eta;
            int charge;

            p_abs=P_abs(px[iTrack] , py[iTrack] , pz[iTrack] );
            pt = Pt(px[iTrack], py[iTrack]);
            eta = Y_Eta(p_abs, pz[iTrack]);
            y = Y_Eta(p0[iTrack], pz[iTrack]);
            phi=Phi(px[iTrack], py[iTrack]);

            fHistPt->Fill(pt);
            fHistEta ->Fill(eta);
            fHistY ->Fill(y);
            fHistP_abs ->Fill(p_abs);
            fHistPhi->Fill(phi);

              } // end of track loop
}//end of event loop

    //  output lists:
    TFile *fileOutput = new TFile( "SMASH_output_histograms.root", "RECREATE" );
    fHistPt->Write();
    fHistEta ->Write();
    fHistY ->Write();
    fHistP_abs ->Write();
    fHistPhi->Write();

    fileOutput->Close();

}
`

**Comment by vks** [comment]
Unfortunately, we currently don't write the charge to the ROOT output (unlike the binary or OSCAR output). This is likely an oversight to be fixed in the next SMASH version.

In principle, the charge can be calculated from the PDG ID, because it includes the quark numbers (see [the definition](pdg.lbl.gov/2018/reviews/rpp2018-rev-monte-carlo-numbering.pdf)). [This](https://github.com/smash-transport/smash/blob/0063efcc88c11151fa4422940a8bd145a52c356d/src/include/smash/pdgcode.h#L470) is how SMASH does it. However, it is a bit complicated. If you are only interested in some particle species, it would be easier to just explicitly compare to the PDG ID like this:

```c++
int sign(int x) {
    if (x < 0) { return -1; } else { return 1; }
}

int q = 0;
switch (abs(pdgcode)) {
    case 2212:  // proton
        q = sign(pdgcode); break;
    case 2112:  // neutron
        q = 0; break;
    // etc.
    default:
}
```

**Comment by gamejad** [comment]
It's a pity. However, thank you for great job!

**Comment by vks** [comment]
The next release of SMASH (version 1.7) will include the particle charge in the ROOT output.
