### ISSUE TITLE
Issues with installing SMASH on Ubuntu

### ISSUE THREAD

**Issue by ejduck3744** [smash-transport/smash#50]
I am trying to install SMASH with Ubuntu (on windows) and I'm running into a problem when I try to run make in the build directory. I have all the prerequisites installed, I use the following cmake options:

$ cmake .. -DGSL_ROOT_DIR=gsl-2.7.1 -DPythia_CONFIG_EXECUTABLE=/home/ejduck3744/pythia8307/bin/pythia8-config -DBoost_INCLUDE_DIR=/boost_1_81_0 -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_COMPILER=g++

and that works without a hitch, but when I try:
$ make

I get a long string of similar errors starting with:

In file included from /usr/include/c++/10/iomanip:43,
                 from /home/ejduck3744/smash-SMASH-2.2/3rdparty/einhard/einhard.hpp:63,
                 from /home/ejduck3744/smash-SMASH-2.2/src/include/smash/logging.h:17,
                 from /home/ejduck3744/smash-SMASH-2.2/src/include/smash/lattice.h:21,
                 from /home/ejduck3744/smash-SMASH-2.2/src/include/smash/action.h:17,
                 from /home/ejduck3744/smash-SMASH-2.2/src/action.cc:10:
/usr/bin/locale:1:1: error: stray â€˜\177â€™ in program
{list of random characters}
/usr/bin/locale:1:5: error: stray â€˜\2â€™ in program
....
and so on, essentially continuing on with a similar error for every few characters in /usr/bin/locale. I think it has to do with character encoding, but trying to convert /usr/bin/locale to UTF-8 doesn't solve the issue. Do you know what is going on?

Thanks for your help!

**Comment by gabriele-inghirami** [comment]
Hi!
Thank you for contacting us!
Unfortunately we use and support only either native GNU/Linux or Mac OS environments, nevertheless let's see if we can help you a bit.
How do you run Ubuntu on Windows?
If you are using Docker or if you can install it, please, notice that we provide images that should work out of the box:
https://github.com/smash-transport/smash/pkgs/container/smash (SMASH only)
https://github.com/smash-transport/smash/pkgs/container/smash-max (SMASH with ROOT, HEPMC3, RIVET and several other tools)

If you using another method, I am not sure to which extent we'll be able to provide support.
Anyway, could you, please, be more specific? Are you using WSL2? Or...?
Which version of Ubuntu have you installed under which version of Windows?
Could you, please, attach the full error log as a .txt file? (You have to use this extension to upload it on Github)
Could you also print the output of:
`printev`
`gcc -v`
`cmake -v`
?
Thank you!

**Comment by AxelKrypton** [comment]
As side comment, from the error message you posted, it looks like that your compiler installation is such that the preprocessor is including `/usr/bin/locale` instead of the C++ `<locale>` header file (included by `<iomanip>`). Since the former is not a C++ file and contains invalid C++ characters, you get then that list of errors. In addition to providing us more information about your Ubuntu installation into Windows (I guess it is done in a virtual machine like VirtualBox or so), please, also run
```console
echo | gcc -Wp,-v -x c++ - -fsyntax-only
```
and tell us what it is printing. This command should tell you where `g++` is looking for system header files. Did you install `g++` yourself? If so, how?

**Comment by ejduck3744** [comment]
Hello,

Yes, I'm using WSL2. Version 2004.2022.1.0
here are the results for your requested commands:
`ejduck3744@PHYS-8CG14319JR:~$ printenv
SHELL=/bin/bash
JUPYTER_CONFIG_DIR=/home/ejduck3744/build/root/etc/notebook
WSL2_GUI_APPS_ENABLED=1
WSL_DISTRO_NAME=Ubuntu
CLING_STANDARD_PCH=none
NAME=PHYS-8CG14319JR
PWD=/home/ejduck3744
LOGNAME=ejduck3744
MANPATH=/home/ejduck3744/build/root/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/mnt/c/root_v5.34.36/man
HOME=/home/ejduck3744
SHLIB_PATH=/home/ejduck3744/build/root/lib
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/198_interop
DYLD_LIBRARY_PATH=/home/ejduck3744/build/root/lib
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
WAYLAND_DISPLAY=wayland-0
CMAKE_PREFIX_PATH=/home/ejduck3744/build/root
LESSCLOSE=/usr/bin/lesspipe %s %s
PYTHONPATH=/home/ejduck3744/build/root/lib
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=ejduck3744
DISPLAY=172.20.96.1:0.0
LIBPATH=/home/ejduck3744/build/root/lib
SHLVL=1
JUPYTER_PATH=/home/ejduck3744/build/root/etc/notebook
ROOTSYS=/home/ejduck3744/build/root
LD_LIBRARY_PATH=/home/ejduck3744/build/root/lib
XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/ejduck3744/build/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/PerkinElmerInformatics/ChemOffice2020/ChemScript/Lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Wolfram Research/WolframScript/:/mnt/c/Program Files/MATLAB/R2020b/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/educkwor/AppData/Local/Microsoft/WindowsApps:/mnt/c/root_v5.34.36/bin:/snap/bin
HOSTTYPE=x86_64
PULSE_SERVER=/mnt/wslg/PulseServer
_=/usr/bin/printenv`

`ejduck3744@PHYS-8CG14319JR:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.3.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-S4I5Pr/gcc-10-10.3.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.3.0 (Ubuntu 10.3.0-1ubuntu1~20.04)`

`ejduck3744@PHYS-8CG14319JR:~$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).`

`ejduck3744@PHYS-8CG14319JR:~$ echo | gcc -Wp,-v -x c++ - -fsyntax-only
ignoring duplicate directory "/usr/include/x86_64-linux-gnu/c++/10"
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/10/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/10
 /usr/include/x86_64-linux-gnu/c++/10
 /usr/include/c++/10/backward
 /usr/lib/gcc/x86_64-linux-gnu/10/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.`

Attached is the error log as well
[troubleshoot.txt](https://github.com/smash-transport/smash/files/10451878/troubleshoot.txt)

I have installed docker, but I've never used it before. 
Thank you for your help!

**Comment by AxelKrypton** [comment]
I allowed myself to edit your post using blocks of triple ticks ` ``` ` to start and end code blocks to make it more readable (see [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for more information).

At first glance, I do not see anything suspicious. I will try to read through more carefully. It is clear that your compiler is finding the wrong _locale_ file, as I wrote before, though. Still, the list of default includes seems fine. Therefore, I would ask you once more to help us with some information.

1. Could you remove everything inside your `build` folder and run again the `cmake [...]` command as well as `VERBOSE=1 make` putting in a txt file the output of both commands? The second will run slower without the `-j` option, but will provide us the information in order of execution, plus it will print the compilation commands.
2. You should then take the last compilation command executed and extract there the input paths given to the compiler and then run `g++ -E -Wp,-v -xc++ <here-the-SMASH-additional-input> /dev/null` with the additional input. This will show where exactly the compiler is looking for includes on your system.

Feel free to do step 1 only and attach here the output, I will then give you the command to run for step 2. I am convinced that we should understand why your compiler finds `/usr/bin/locale` from  `#include <locale>`.

**Comment by ejduck3744** [comment]
Here are the log files! thank you for your help!
[cmake_log.txt](https://github.com/smash-transport/smash/files/10459645/cmake_log.txt)
[make_log.txt](https://github.com/smash-transport/smash/files/10459646/make_log.txt)

**Comment by AxelKrypton** [comment]
From the *make_log.txt* file you can see that the compiler is invoked with `-isystem /usr/bin`, which then lead to the error you get, since it instructs the compiler to look for header files in the ***/usr/bin*** folder and this is **NOT** what you want.

Looking at your `cmake` command output, I noticed the line `Found GSL: /usr/bin` and I am 99% sure this is the culprit. In this issue description you mention that you pass `-DGSL_ROOT_DIR=gsl-2.7.1` to `cmake` command. Is there a specific reason for you to do so? CMake should find a system-wide installation without need of help. For example, that line of my CMake output on my Ubuntu machine reads `Found GSL: /usr/include`, which make much more sense, since header files should be in an ***include*** folder and in any case well separated from the binaries.

I would
* first try not to pass this option at all to `cmake` and see if it finds GSL as well (if not, please attach a file with that `cmake` output) and
* if this does not work, try to use a global path using that option, something like `-DGSL_ROOT_DIR=/global/path/to/gsl-2.7.1`.

Let me know if something succeeds and if both approaches above do not change anything, you should provide us more information about how/where you installed the GSL library. For example, installing it, you should have a binary file in the specified `${PREFIX}/bin` folder which is called `gsl-config`. On my machine `PREFIX=/usr` as it usually is for system-wide installations and then I can run
```console
$ /usr/bin/gsl-config --cflags
-I/usr/include
```
to confirm where the library header files are. What does the command `locate gsl-config` give in your case?

**Comment by ejduck3744** [comment]
INSTALLED!!!! Thank you!!

You were right about where the issue turned out to be. It turns out it was finding this package: https://gsl.readthedocs.io/en/latest/

which I had installed for another project. I uninstalled that and I was able to fully install SMASH.

**Comment by AxelKrypton** [comment]
Very happy you managed. 😊 ...I will then close this issue, but feel free to reopen it or open another one in case of need.
