### ISSUE TITLE
Feature request: inclusion of information about time of last collision in .root-data file

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#6]
Dear SMASH team!

I would like to ask if it would be possible to add an option to SMASH to save the info about time of last collision of a single particle in .root file (such as it realized in .oscar file).

It can provide us an ability to separate particles-participants and particles-spectators, which can give us some usefull information for physical analysis.

**Comment by stdnmr** [comment]
Thanks for the input. 

We are trying to add the extended ROOT output (which would include the time of last collision) for the next release. 

I will update this issue if we are certain that it will be included in the next release.

**Comment by vks** [comment]
The upcoming SMASH 1.7 release will support the extended output for ROOT files.
