### ISSUE TITLE
Feature request: Event regeneration in case of it is empty

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#7]
Hi!

Generating events with quadratic distributed impact-parameter in range [0,20] fm I found out that about 46% of events are empty. I think that it will very convenient and practical if there is ability to REgenerate event if it is empty right in the generation process. At least, it will save the disk space, decrease  time of data analysis code flow and allow us have so good statistic as we need (instead 1/2 of this).

Thank you in advance.

**Comment by vks** [comment]
This unfortunately common (the most common events in the minimum-bias impact-parameter distribution can usually not be measured in experiment). If you know the impact-parameter distribution of non-empty events (or determine it by running SMASH), you can use `Modi: Collider: Impact: "custom"` to mostly avoid empty events.

I think regenerating empty events makes sense, even if it only saves some space, unlike changing the impact parameter distribution directly as suggested above, which also improves runtime.

**Comment by gamejad** [comment]
Honestly saying, runtime is not problem since we use computer clusters. Using a custom impact-parameter distribution instead quadratic does not guarantee the full exclusion of empty events. Also, it should lead to some (minor, but...) deformation of impact-parameter distribution. We would like to avoid it.

**Comment by stdnmr** [comment]
The requested feature will be in the next release.

**Comment by stdnmr** [comment]
The requested feature was released with `SMASH-1.8`, see the CHANGELOG or the User Guide for more information.

**Comment by vks** [comment]
This is the corresponding part of the changelog:
> The `Only_Final` option for the Particles output has the new possibility if `IfNotEmpty` is entered. Then only output is written if the event is not empty i.e. there was a collision between projectile and target to save disk space. The other two options are now `Yes` or `No` (previously `True` or `False`).

This is not the same as regenerating events (which would be tricky to implement for technical reasons), but it achieves the desired saving of space by not outputting empty events. However, increasing the total number of simulated events by the expected number of empty events achieves a similar effect as regenerating empty events.
