### ISSUE TITLE
Fixed plane of reaction 

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#8]
Hi!

I have found out that plane of reaction (plane which impact-parameter vector lead in) is XZ plane always. Of course, it is very useful for flows studies, but it leads to anisotropy of phi-distribution in event-by-event analysis. 

![Снимок экрана от 2019-11-17 20-10-34](https://user-images.githubusercontent.com/48550409/69373107-26091f00-0cb4-11ea-86cc-0ec76c418262.png)

Can plane reaction be variable by some settings on or can it become variable in the next versions of SMASH?

**Comment by stdnmr** [comment]
Just to make sure we understand your request correctly first: The idea is that (effectively) the impact parameter vector would be randomly rotated in XY plane, right?

We follow the convention that the x axis is always alined along the impact parameter (vector). You could also achieve what you want in the analysis by rotating the coordinates in the output in your analysis.

May I ask what the background of your request is?

**Comment by gamejad** [comment]
> The idea is that (effectively) the impact parameter vector would be randomly rotated in XY plane, right?
Yes, exactly. My present task is creation of realistic physical observables distributions, and I just trying to level down some artificially created ... features, call it that. 
I understand that we can rotate coordinates in output data instead rotation of impact parameter while generating process. For me it is just preferable to increase computational complexity of generating process instead output data processing since we have an access to some powerful computer clusters.

**Comment by justinmohs** [comment]
There is a new option "Random_Reaction_Plane" in the in smash-1.8 that rotates the initial positions of nucleons by a random angle around the z-axis (see [user guide](http://theory.gsi.de/~smash/userguide/1.8/input_impact_parameter_.html)) 
Using this option one obtains a flat distribution in phi when averaging over many events.
