### ISSUE TITLE
Using a multicore processors in generation process

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash#9]
Hi!

Can I speed up a SMASH generation process via using more then 1 core of my processor? Of course, I can use few terminals to generate data files simultaneously , but it leads to increasing of data files numbers and a little chaos in data-directory. So I am trying to find out more elegant way to speed up calculations than the above.

Thank you in advance.

**Comment by vks** [comment]
Currently SMASH only uses one core, so running several instances in parallel is the recommended way to speed up calculations.

> Of course, I can use few terminals to generate data files simultaneously , but it leads to increasing of data files numbers and a little chaos in data-directory.

What we usually do is to write a script that runs SMASH in parallel and specifies a different output directory for each instance of SMASH via the `-o` flag. For example, see the following `sh` script running SMASH on 10 cores:

```sh
for i in {0..10}; do
    mkdir -p data/$i
    ./smash -o data/$i > data/$i/smash.log &
done
```

This requires only one terminal and the data files are ordered as specified by the script. Does this solve your problem?

**Comment by gamejad** [comment]
Honestly saying, the number of opened terminal windows is not the big problem for me)

I was just interested about a possibility to make some things a little bit accurate, but , of course, the necessity to create 10 output-files instead 1 is really minor problem since we use TChain in ROOT.

Anyway, thank you!
